TRAIN:
  WARMUP_EPOCHS: 5
  EPOCHS: 300
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.05
  OPTIMIZER: 
    NAME: adamw
#DATA:
  # BATCH_SIZE: 512
AUG:
  SSL_AUG: True
  SSL_AUG_TYPE: byol
MODEL:
  TYPE: dino
  ENCODER: swin_base
  NAME: dino__swin_base__odpr02_tdpr0_cm0996_out65536_proj3
  ONLINE_DROP_PATH_RATE: 0.2
  TARGET_DROP_PATH_RATE: 0.0
  CONTRAST_MOMENTUM: 0.996
  PROJ_NUM_LAYERS: 3
  DINO_OUT_DIM: 65536
  DINO_HIDDEN_DIM: 2048
  DINO_BOTTLENECK_DIM: 256
  DINO_USE_BN_IN_HEAD: False
  DINO_NORM_LAST_LAYER: True
  DINO_STUDENT_TEMP: 0.1
  DINO_TEACHER_TEMP: 0.04
  DINO_WARMUP_TEACHER_TEMP: 0.04
  DINO_WARMUP_TEACHER_TEMP_EPOCHS: 30
  DINO_CENTER_MOMENTUM: 0.9
  DINO_FREEZE_LAST_LAYER_EPOCHS: 1
