#!/bin/bash
#PBS -N dino_swint
#PBS -lselect=1:ncpus=16:mem=128gb:ngpus=4
#PBS -lwalltime=72:00:00

cd $PBS_O_WORKDIR

MASTER_PORT=$((10000 + RANDOM % 50000))
DATA_PATH="$HOME/datasets/imagenet/"
OUTPUT_DIR="./logs/"
TAG="default"

source $HOME/anaconda3/bin/activate
source activate vitamins

python -m torch.distributed.launch \
    --nproc_per_node=4 \
    --master_port=$MASTER_PORT \
    main_pretrain.py \
    --cfg configs/dino/swin_tiny.yaml \
    --data-path $DATA_PATH \
    --batch-size 128 \
    --output $OUTPUT_DIR \
    --tag $TAG

python -m torch.distributed.launch \
    --nproc_per_node=4 \
    --master_port=$MASTER_PORT \
    main_linear.py \
    --cfg configs/dino/swin_tiny.yaml \
    --data-path $DATA_PATH \
    --output $OUTPUT_DIR \
    --tag $TAG
